 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/miniflux:$COMMIT_SHA', '-f', 'packaging/docker/Dockerfile','.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'asia.gcr.io/$PROJECT_ID/miniflux:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'miniflux'
   - '--image'
   - 'asia.gcr.io/$PROJECT_ID/miniflux:$COMMIT_SHA'
   - '--region'
   - 'asia-northeast1'
   - '--platform'
   - 'managed'
 images:
 - 'asia.gcr.io/$PROJECT_ID/miniflux:$COMMIT_SHA'

